# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default         
  demands:               # Optional: Specify any additional demands your self-hosted agent should meet
  - Agent.Name -equals chepopo-dell


steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- script: dotnet build --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Build .NET Core project'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false
  displayName: 'Publish .NET Core project'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- script: |
      dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source "hello-world" --api-key $(az)
  displayName: 'Push to Azure Artifacts'