# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default         
  demands:              
  - Agent.Name -equals chepopo-dell


steps:

# Install OpenSSL if required (modify if a specific version is needed)
- script: |
    sudo apt update
    sudo apt install -y openssl
  displayName: 'Install OpenSSL (if required)'


- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 8.x 
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'  
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false
  displayName: 'Publish .NET Core project'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- script: |
      dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source "hello-world" --api-key $(az)
  displayName: 'Push to Azure Artifacts'