# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main


pool:
  name: Default         
  demands:              
  - Agent.Name -equals chepopo-dell

steps:

- script: |
    echo "Source Directory: $(Build.SourcesDirectory)"
  displayName: 'Print Source Directory'

- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 8.x 
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'  
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false
  displayName: 'Publish .NET Core project'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- script: dotnet pack -p Version=1.0.$(Build.BuildId)
  displayName: 'Packing app'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/home/kuper/ALL_WS/azure-devops-project/myagent/_work/1/s/bin/Release/HelloWorld.1.0.0.nupkg'
    artifact: 'HelloWorld.1.0.0'
    publishLocation: 'pipeline'
  displayName: 'Publish NuGet package as pipeline artifact'

- script: |
        dotnet nuget push --source https://pkgs.dev.azure.com/kupkup1992/Hello-Wold/_packaging/hello-world/nuget/v3/index.json --api-key $(az) $(System.DefaultWorkingDirectory)/bin/Release/*.nupkg
  displayName: 'Push to Azure Artifacts'
